export const products = [
  {
    id: 1,
    name: "Iphone 15",
    brand: "Apple",
    category: "Mobile",
    price: 75000,
    image_url: "/products/iphone%2015.jpg",
    product_url: "",
  },
  {
    id: 2,
    name: "Iphone 16",
    brand: "Apple",
    category: "Mobile",
    price: 90000,
    image_url: "/products/iphone%2016.avif",
    product_url: "",
  },
  {
    id: 3,
    name: "Iphone 17",
    brand: "Apple",
    category: "Mobile",
    price: 95000,
    image_url: "/products/iphone%2017.jpg",
    product_url: "",
  },
  {
    id: 4,
    name: "Campus Shoes",
    brand: "Campus",
    category: "Shoes",
    price: 4450,
    image_url: "/products/campus%20shoes.jpg",
    product_url: "https://www.campusshoes.com/products/first-wht-sil-borg-mens-running-shoes?srsltid=AU7gw4V1O7Fa8Q2-emDG3cGIbxarek9k71FKsriiRPehpnYLGdv-fcqJ",
  },
  {
    id: 5,
    name: "Nike Tennis Shoes",
    brand: "Nike",
    category: "Shoes",
    price: 9000,
    image_url: "/products/nike%20tennis.jpg",
    product_url: "",
  },
  {
    id: 6,
    name: "One8 Shoes",
    brand: "One8",
    category: "Shoes",
    price: 9500,
    image_url: "/products/one8%20shoes.webp",
    product_url: "",
  },
  {
    id: 7,
    name: "Bellavita Perfume",
    brand: "Bellavita",
    category: "Perfume",
    price: 1990,
    image_url: "/products/bellavita.jpg",
    product_url: "",
  },
  {
    id: 8,
    name: "Blue Ocean Perfume",
    brand: "Blue Ocean",
    category: "Perfume",
    price: 2000,
    image_url: "/products/blue%20ocean.jpg",
    product_url: "",
  },
  {
    id: 9,
    name: "Ustraa Perfume",
    brand: "Ustraa",
    category: "Perfume",
    price: 2100,
    image_url: "/products/ustraa.jpg",
    product_url: "",
  },
  {
    id: 10,
    name: "Titan 90223BM01",
    brand: "TITAN",
    category: "Watch",
    price: 16000,
    image_url: "/products/titan%2090223bm01.webp",
    product_url: "",
  },
  {
    id: 11,
    name: "Titan 1830KL02",
    brand: "TITAN",
    category: "Watch",
    price: 17000,
    image_url: "/products/titan%201830kl02.webp",
    product_url: "",
  },
  {
    id: 12,
    name: "Titan 1830YM02",
    brand: "TITAN",
    category: "Watch",
    price: 18000,
    image_url: "/products/titan%201830ym02.webp",
    product_url: "",
  },
];